//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNSC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyDojuUQ75t-iqa3FxChN2Qsqq_d_EchEkI")]
        public string YtApiKey {
            get {
                return ((string)(this["YtApiKey"]));
            }
            set {
                this["YtApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string StreamerBotIp {
            get {
                return ((string)(this["StreamerBotIp"]));
            }
            set {
                this["StreamerBotIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6969")]
        public string StreamerBotPort {
            get {
                return ((string)(this["StreamerBotPort"]));
            }
            set {
                this["StreamerBotPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.42.110")]
        public string ObsIp {
            get {
                return ((string)(this["ObsIp"]));
            }
            set {
                this["ObsIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1402")]
        public string ObsPort {
            get {
                return ((string)(this["ObsPort"]));
            }
            set {
                this["ObsPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nimda1402")]
        public string ObsPassword {
            get {
                return ((string)(this["ObsPassword"]));
            }
            set {
                this["ObsPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("537f127a-5066-4166-a32d-b57e15fb5786")]
        public string SendMessageActionID {
            get {
                return ((string)(this["SendMessageActionID"]));
            }
            set {
                this["SendMessageActionID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SendMessageToChat")]
        public string SendMessageActionName {
            get {
                return ((string)(this["SendMessageActionName"]));
            }
            set {
                this["SendMessageActionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SC] Info")]
        public string MainTextSource {
            get {
                return ((string)(this["MainTextSource"]));
            }
            set {
                this["MainTextSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SC] Round")]
        public string RoundHeaderSource {
            get {
                return ((string)(this["RoundHeaderSource"]));
            }
            set {
                this["RoundHeaderSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SC] Countdown 60")]
        public string CountdownSource {
            get {
                return ((string)(this["CountdownSource"]));
            }
            set {
                this["CountdownSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Votes")]
        public string AllVotesSource {
            get {
                return ((string)(this["AllVotesSource"]));
            }
            set {
                this["AllVotesSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[NS] Song Championship")]
        public string ChampionshipScene {
            get {
                return ((string)(this["ChampionshipScene"]));
            }
            set {
                this["ChampionshipScene"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SC] Left Player")]
        public string LeftPlayerSource {
            get {
                return ((string)(this["LeftPlayerSource"]));
            }
            set {
                this["LeftPlayerSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SC] Right Player")]
        public string RightPlayerSource {
            get {
                return ((string)(this["RightPlayerSource"]));
            }
            set {
                this["RightPlayerSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Winner")]
        public string WinnerSource {
            get {
                return ((string)(this["WinnerSource"]));
            }
            set {
                this["WinnerSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VS")]
        public string VsSource {
            get {
                return ((string)(this["VsSource"]));
            }
            set {
                this["VsSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SC] Votes left")]
        public string LeftVotesSource {
            get {
                return ((string)(this["LeftVotesSource"]));
            }
            set {
                this["LeftVotesSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SC] Votes right")]
        public string RightVotesSource {
            get {
                return ((string)(this["RightVotesSource"]));
            }
            set {
                this["RightVotesSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SendWhisper")]
        public string SendWhisperActionName {
            get {
                return ((string)(this["SendWhisperActionName"]));
            }
            set {
                this["SendWhisperActionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8a9381a5-67fd-45e0-afb6-b774311797f2")]
        public string SendWhisperActionID {
            get {
                return ((string)(this["SendWhisperActionID"]));
            }
            set {
                this["SendWhisperActionID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SC] Winner Top")]
        public string WinnerTopSource {
            get {
                return ((string)(this["WinnerTopSource"]));
            }
            set {
                this["WinnerTopSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SC] Winner Bottom")]
        public string WinnerBottomSource {
            get {
                return ((string)(this["WinnerBottomSource"]));
            }
            set {
                this["WinnerBottomSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\SB Extensions\\SongChampionships")]
        public string WebserverPath {
            get {
                return ((string)(this["WebserverPath"]));
            }
            set {
                this["WebserverPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://discord.com/api/webhooks/1083726664443379714/dE_HH5mjyJnP6u2LnyJ8YHNGltCA" +
            "Ih0shlCUZywcXKifpzeVU7z5d7voWNeJnqIQbbFF")]
        public string WebhookUrl {
            get {
                return ((string)(this["WebhookUrl"]));
            }
            set {
                this["WebhookUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MainCam Center")]
        public string CenterFilterName {
            get {
                return ((string)(this["CenterFilterName"]));
            }
            set {
                this["CenterFilterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MainCam Corner")]
        public string CornerFilterName {
            get {
                return ((string)(this["CornerFilterName"]));
            }
            set {
                this["CornerFilterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FNSC")]
        public string MainChampionshipScene {
            get {
                return ((string)(this["MainChampionshipScene"]));
            }
            set {
                this["MainChampionshipScene"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoBuddyIsPerfect")]
        public string StreamerName {
            get {
                return ((string)(this["StreamerName"]));
            }
            set {
                this["StreamerName"] = value;
            }
        }
    }
}
